### PR TITLE
fix (aarch64): pixi bin to the PATH and add bluefin-cli packages for pixi

### LINKED ISSUE #377: GDX: add `~/.pixi/bin` to `$PATH`
needed for new binaries to work like brew

### LINKED ISSUE #387: `~.pixi/bin` needs to be added to the path
We forgot to add adding the pixi path to the user's home directory.

### LINKED ISSUE #388: Use pixi for bluefin-cli
Another arm specific issue, it would be nice if we could get the same setup with pixi. This is low priority.

### PR DESCRIPTION
**Pull request by hanthor**

### CODE REVIEW

**Review by tulilirockz — DISMISSED** [review]
You probably want to just add this on profile.d just like the brew.sh script we have there now

**Comment by hanthor** [comment]
I did it betterer

**Comment by hanthor** [comment]
Ive tested this locally and it works....had to manually rin my version of ublue-bling

File: system_files_overrides/aarch64/etc/profile.d/pixi.sh [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+if [[ -d "$PIXI_BIN_DIR" ]]; then
+  if [[ ":$PATH:" != *":$PIXI_BIN_DIR:"* ]]; then
+    export PATH="$PIXI_BIN_DIR:$PATH"
+    echo "Added pixi bin directory to PATH: $PIXI_BIN_DIR"
+  else
+    echo "pixi bin directory already in PATH."
+  fi
+else
+  echo "pixi bin directory not found: $PIXI_BIN_DIR"
+fi
```
Comment (tulilirockz) [inline system_files_overrides/aarch64/etc/profile.d/pixi.sh]:
```suggestion
if [[ -d "$PIXI_BIN_DIR" ]]; then
  if [[ ":$PATH:" != *":$PIXI_BIN_DIR:"* ]]; then
    export PATH="$PIXI_BIN_DIR:$PATH"
  fi
fi
```
We dont want the logging, itll show up by default on people's shells and itll be annoying

**Review by tulilirockz — APPROVED** [review]
Looks amazing. Thank you for this!
