### PR TITLE
Fix: Slow login times when password is typed wrong

### LINKED ISSUE #305: Slow login times when password is typed wrong
For some reason GNOME is getting the same motd that you get when you ssh into a system. That is making it write line-by-line it, making it take like 1-2 seconds longer when you get a password wrong when login in through GDM

### PR DESCRIPTION
**Pull request by hanthor**
Fixes #305

### CODE REVIEW

File: build_scripts/40-services.sh [hunk 1]
```diff
@@ -22,6 +22,9 @@ systemctl --global enable ublue-user-setup.service
 systemctl mask bootc-fetch-apply-updates.timer bootc-fetch-apply-updates.service
 systemctl enable check-sb-key.service
 
+# Disable lastlog display on previous failed login in GDM (This makes logins slow)
+sudo authselect enable-feature with-silent-lastlog
```
Comment (tulilirockz) [inline build_scripts/40-services.sh]:
```suggestion
authselect enable-feature with-silent-lastlog
```

No need for sudo anywhere on the container I think

**Review by tulilirockz — APPROVED** [review]
